name: ml4t
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- cycler
- kiwisolver
- matplotlib
- numpy
- pandas
- pyparsing
- python-dateutil
- pytz
- scipy
- seaborn
- six
- joblib
- pytest
- pytest-json
- future
- pprofile
- pip
- pip:
  - jsons==0.8.8
  - gradescope-utils
  - subprocess32